# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AcsUser
    from ._models_py3 import BatchIdentityResponse
    from ._models_py3 import BatchToken
    from ._models_py3 import BatchTokenRequest
    from ._models_py3 import BatchTokenResponse
    from ._models_py3 import ResourceRequest
    from ._models_py3 import ResourceRevocationEventRequest
    from ._models_py3 import TokenRequest
    from ._models_py3 import TokenResponse
    from ._models_py3 import UserRevocationEventRequest
except (SyntaxError, ImportError):
    from ._models import AcsUser  # type: ignore
    from ._models import BatchIdentityResponse  # type: ignore
    from ._models import BatchToken  # type: ignore
    from ._models import BatchTokenRequest  # type: ignore
    from ._models import BatchTokenResponse  # type: ignore
    from ._models import ResourceRequest  # type: ignore
    from ._models import ResourceRevocationEventRequest  # type: ignore
    from ._models import TokenRequest  # type: ignore
    from ._models import TokenResponse  # type: ignore
    from ._models import UserRevocationEventRequest  # type: ignore

__all__ = [
    'AcsUser',
    'BatchIdentityResponse',
    'BatchToken',
    'BatchTokenRequest',
    'BatchTokenResponse',
    'ResourceRequest',
    'ResourceRevocationEventRequest',
    'TokenRequest',
    'TokenResponse',
    'UserRevocationEventRequest',
]
