# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import msrest.serialization


class TokenRequest(msrest.serialization.Model):
    """TokenRequest.

    All required parameters must be populated in order to send to Azure.

    :param identity:
    :type identity: str
    :param scopes: Required.
    :type scopes: list[str]
    """

    _validation = {
        'scopes': {'required': True},
    }

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'str'},
        'scopes': {'key': 'scopes', 'type': '[str]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TokenRequest, self).__init__(**kwargs)
        self.identity = kwargs.get('identity', None)
        self.scopes = kwargs['scopes']


class TokenResponse(msrest.serialization.Model):
    """TokenResponse.

    :param identity:
    :type identity: str
    :param token:
    :type token: str
    :param expires_in:
    :type expires_in: int
    """

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'str'},
        'token': {'key': 'token', 'type': 'str'},
        'expires_in': {'key': 'expiresIn', 'type': 'int'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TokenResponse, self).__init__(**kwargs)
        self.identity = kwargs.get('identity', None)
        self.token = kwargs.get('token', None)
        self.expires_in = kwargs.get('expires_in', None)
