# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LinkNotificationHubParameters(Model):
    """Description of an Azure Notification Hub to link to the communication
    service.

    All required parameters must be populated in order to send to Azure.

    :param resource_id: Required. The resource ID of the notification hub
    :type resource_id: str
    :param connection_string: Required. Connection string for the notification
     hub
    :type connection_string: str
    """

    _validation = {
        'resource_id': {'required': True},
        'connection_string': {'required': True},
    }

    _attribute_map = {
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'connection_string': {'key': 'connectionString', 'type': 'str'},
    }

    def __init__(self, *, resource_id: str, connection_string: str, **kwargs) -> None:
        super(LinkNotificationHubParameters, self).__init__(**kwargs)
        self.resource_id = resource_id
        self.connection_string = connection_string
