# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AddChatThreadMembersRequest
    from ._models_py3 import ChatMessage
    from ._models_py3 import ChatThread
    from ._models_py3 import ChatThreadInfo
    from ._models_py3 import ChatThreadMember
    from ._models_py3 import CreateChatThreadRequest
    from ._models_py3 import CreateChatThreadResult
    from ._models_py3 import ListChatMessagesResult
    from ._models_py3 import ListChatThreadsResult
    from ._models_py3 import PostReadReceiptRequest
    from ._models_py3 import ReadReceipt
    from ._models_py3 import SendChatMessageRequest
    from ._models_py3 import SendChatMessageResult
    from ._models_py3 import UpdateChatMessageRequest
    from ._models_py3 import UpdateChatThreadRequest
except (SyntaxError, ImportError):
    from ._models import AddChatThreadMembersRequest  # type: ignore
    from ._models import ChatMessage  # type: ignore
    from ._models import ChatThread  # type: ignore
    from ._models import ChatThreadInfo  # type: ignore
    from ._models import ChatThreadMember  # type: ignore
    from ._models import CreateChatThreadRequest  # type: ignore
    from ._models import CreateChatThreadResult  # type: ignore
    from ._models import ListChatMessagesResult  # type: ignore
    from ._models import ListChatThreadsResult  # type: ignore
    from ._models import PostReadReceiptRequest  # type: ignore
    from ._models import ReadReceipt  # type: ignore
    from ._models import SendChatMessageRequest  # type: ignore
    from ._models import SendChatMessageResult  # type: ignore
    from ._models import UpdateChatMessageRequest  # type: ignore
    from ._models import UpdateChatThreadRequest  # type: ignore

from ._azure_communication_chat_service_enums import (
    ChatMessagePriority,
)

__all__ = [
    'AddChatThreadMembersRequest',
    'ChatMessage',
    'ChatThread',
    'ChatThreadInfo',
    'ChatThreadMember',
    'CreateChatThreadRequest',
    'CreateChatThreadResult',
    'ListChatMessagesResult',
    'ListChatThreadsResult',
    'PostReadReceiptRequest',
    'ReadReceipt',
    'SendChatMessageRequest',
    'SendChatMessageResult',
    'UpdateChatMessageRequest',
    'UpdateChatThreadRequest',
    'ChatMessagePriority',
]
