# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AddThreadMembersRequest
    from ._models_py3 import CreateThreadRequest
    from ._models_py3 import CreateThreadResult
    from ._models_py3 import ListMessagesResult
    from ._models_py3 import ListThreadsResult
    from ._models_py3 import Message
    from ._models_py3 import PostReadReceiptRequest
    from ._models_py3 import ReadReceipt
    from ._models_py3 import SendMessageRequest
    from ._models_py3 import SendMessageResult
    from ._models_py3 import Thread
    from ._models_py3 import ThreadInfo
    from ._models_py3 import ThreadMember
    from ._models_py3 import UpdateMessageRequest
    from ._models_py3 import UpdateThreadRequest
except (SyntaxError, ImportError):
    from ._models import AddThreadMembersRequest  # type: ignore
    from ._models import CreateThreadRequest  # type: ignore
    from ._models import CreateThreadResult  # type: ignore
    from ._models import ListMessagesResult  # type: ignore
    from ._models import ListThreadsResult  # type: ignore
    from ._models import Message  # type: ignore
    from ._models import PostReadReceiptRequest  # type: ignore
    from ._models import ReadReceipt  # type: ignore
    from ._models import SendMessageRequest  # type: ignore
    from ._models import SendMessageResult  # type: ignore
    from ._models import Thread  # type: ignore
    from ._models import ThreadInfo  # type: ignore
    from ._models import ThreadMember  # type: ignore
    from ._models import UpdateMessageRequest  # type: ignore
    from ._models import UpdateThreadRequest  # type: ignore

from ._azure_communication_chat_service_enums import (
    MessagePriority,
)

__all__ = [
    'AddThreadMembersRequest',
    'CreateThreadRequest',
    'CreateThreadResult',
    'ListMessagesResult',
    'ListThreadsResult',
    'Message',
    'PostReadReceiptRequest',
    'ReadReceipt',
    'SendMessageRequest',
    'SendMessageResult',
    'Thread',
    'ThreadInfo',
    'ThreadMember',
    'UpdateMessageRequest',
    'UpdateThreadRequest',
    'MessagePriority',
]
