# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CreateMessageResponse(Model):
    """CreateMessageResponse.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: The Id of the message. This Id is server generated.
    :vartype id: str
    :ivar client_message_id: This Id is a client-specific Id in a numeric
     unsigned Int64 format. It can be used for client deduping, among other
     client usages.
    :vartype client_message_id: str
    """

    _validation = {
        'id': {'readonly': True},
        'client_message_id': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'client_message_id': {'key': 'clientMessageId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(CreateMessageResponse, self).__init__(**kwargs)
        self.id = None
        self.client_message_id = None
