# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PostReadReceiptRequest(Model):
    """PostReadReceiptRequest.

    All required parameters must be populated in order to send to Azure.

    :param client_message_id: Required. The client message Id specified when
     the message was sent.
     This Id is a client-specific Id in a numeric unsigned Int64 format. It can
     be used for client deduping, among other client usages.
    :type client_message_id: str
    :param message_id: Required. Id of the latest message read by current
     user.
    :type message_id: str
    """

    _validation = {
        'client_message_id': {'required': True},
        'message_id': {'required': True},
    }

    _attribute_map = {
        'client_message_id': {'key': 'clientMessageId', 'type': 'str'},
        'message_id': {'key': 'messageId', 'type': 'str'},
    }

    def __init__(self, *, client_message_id: str, message_id: str, **kwargs) -> None:
        super(PostReadReceiptRequest, self).__init__(**kwargs)
        self.client_message_id = client_message_id
        self.message_id = message_id
