# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThreadInfo(Model):
    """ThreadInfo.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Thread id.
    :vartype id: str
    :param topic: Thread topic.
    :type topic: str
    :param is_deleted: Flag if a thread is soft deleted.
    :type is_deleted: bool
    :ivar last_message_received_time: The timestamp when the last message
     arrived at the server. The timestamp is in ISO8601 format:
     `yyyy-MM-ddTHH:mm:ssZ`.
    :vartype last_message_received_time: datetime
    """

    _validation = {
        'id': {'readonly': True},
        'last_message_received_time': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'topic': {'key': 'topic', 'type': 'str'},
        'is_deleted': {'key': 'isDeleted', 'type': 'bool'},
        'last_message_received_time': {'key': 'lastMessageReceivedTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, topic: str=None, is_deleted: bool=None, **kwargs) -> None:
        super(ThreadInfo, self).__init__(**kwargs)
        self.id = None
        self.topic = topic
        self.is_deleted = is_deleted
        self.last_message_received_time = None
