# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import List, Optional

import msrest.serialization


class TokenRequest(msrest.serialization.Model):
    """TokenRequest.

    :param identity:
    :type identity: str
    :param scopes:
    :type scopes: list[str]
    """

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'str'},
        'scopes': {'key': 'scopes', 'type': '[str]'},
    }

    def __init__(
        self,
        *,
        identity: Optional[str] = None,
        scopes: Optional[List[str]] = None,
        **kwargs
    ):
        super(TokenRequest, self).__init__(**kwargs)
        self.identity = identity
        self.scopes = scopes


class TokenResponse(msrest.serialization.Model):
    """TokenResponse.

    :param acs_identity:
    :type acs_identity: str
    :param token:
    :type token: str
    :param expires_in:
    :type expires_in: int
    """

    _attribute_map = {
        'acs_identity': {'key': 'acsIdentity', 'type': 'str'},
        'token': {'key': 'token', 'type': 'str'},
        'expires_in': {'key': 'expiresIn', 'type': 'int'},
    }

    def __init__(
        self,
        *,
        acs_identity: Optional[str] = None,
        token: Optional[str] = None,
        expires_in: Optional[int] = None,
        **kwargs
    ):
        super(TokenResponse, self).__init__(**kwargs)
        self.acs_identity = acs_identity
        self.token = token
        self.expires_in = expires_in
