# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import msrest.serialization


class TokenRequest(msrest.serialization.Model):
    """TokenRequest.

    :param identity:
    :type identity: str
    :param scopes:
    :type scopes: list[str]
    """

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'str'},
        'scopes': {'key': 'scopes', 'type': '[str]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TokenRequest, self).__init__(**kwargs)
        self.identity = kwargs.get('identity', None)
        self.scopes = kwargs.get('scopes', None)


class TokenResponse(msrest.serialization.Model):
    """TokenResponse.

    :param acs_identity:
    :type acs_identity: str
    :param token:
    :type token: str
    :param expires_in:
    :type expires_in: int
    """

    _attribute_map = {
        'acs_identity': {'key': 'acsIdentity', 'type': 'str'},
        'token': {'key': 'token', 'type': 'str'},
        'expires_in': {'key': 'expiresIn', 'type': 'int'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TokenResponse, self).__init__(**kwargs)
        self.acs_identity = kwargs.get('acs_identity', None)
        self.token = kwargs.get('token', None)
        self.expires_in = kwargs.get('expires_in', None)
